config/routes.rb
ResourceIt::Application.routes.draw do
  resources :users, except: [:show , :new]
  resources :sessions, only: [:create]
  resources :tags
  get "/create_snippet" => 'snippets#create'
  get "/snippets" => "snippets#index"
  match '/signin' => 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile', to: 'users#show'
  match '/signup', to: 'users#new'
  root to: "users#new"

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :content, :user_id

  validates :content, :user_id, presence: true
  belongs_to :user
  has_and_belongs_to_many :tags


  def create_tags(tags)
    tags = Tag.sanitize_tags(tags)
    tags.each do |tag|
      self.tags << Tag.find_or_create_by_content(tag)
    end
  end


  default_scope order('created_at DESC')
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :content

  validates :content, presence: true, uniqueness: { case_sensitive: false }
  has_and_belongs_to_many :snippets

  def self.sanitize_tags(tags)
    tags.split(' ').map do |tag|
      tag.downcase
    end
  end

  default_scope joins: :snippets, group: "tags.id", order: "snippets.count desc"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password
  has_secure_password
  before_save :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, presence: true

  has_many :snippets, dependent: :destroy
  has_many :tags , through: :snippets

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  after_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = 'http://snipp-et.herokuapp.com' 
    headers['Access-Control-Request-Method'] = '*' 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "Successfully logged in"
      redirect_to '/profile' 
    else
      flash.now[:error] = "Invalid Email/Password combination"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def create

    user = User.find_by_remember_token(params[:token])
    redirect_to root_url unless signed_in?
    snippet = user.snippets.build(content: params[:content]) if user

    if snippet.save
      snippet.create_tags(params[:tags])
    end
  end


  def index
    redirect_to root_path unless current_user
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

	def index
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
    @snippets = @tag.snippets.where(user_id: current_user.id)
  end


  def index 
    redirect_to root_path unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :js, :html
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
    end
  end

  def show
    redirect_to root_path unless current_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarklet_helper.rb
module BookmarkletHelper

	def bookmarklet_caller_js
	  base_url = Rails.env.development? ? "http://#{request.host_with_port}/" : "https://#{request.host_with_port}/"
		js = <<-JS
		(function (){
			var script = document.createElement('SCRIPT');
			script.src = '#{base_url}assets/bookmarklet_js.js';
			script.setAttribute('data-bookmarklet-token', '#{current_user.remember_token}');
			document.body.appendChild(script);
		})();
		JS
		js.split("\n").map(&:strip).join('')
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:token] = user.id
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_id(cookies[:token])
	end

	def signed_in?
		current_user.present?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:token)
	end
end

app/views/layouts/_signed_in.html.erb
 <div class="signed-in">
   <% if signed_in? %>
     <%= link_to "LogOut", signout_path, method: :delete %> 
    <%= link_to "Profile", '/profile' %>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResourceIt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :page_specific_javascript %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert") %>
  <% end %>
  <h1 class="logo"><%= link_to "Snipp-et", root_path %></h1>
    <%= render 'layouts/signed_in' %>
  </nav>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <ul>
    	<li><%= msg %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_user_fields.html.erb
<%= f.text_field :email, placeholder: "Email" %>
<%= f.password_field :password, placeholder: "Password" %>

app/views/snippets/index.html.erb
<div class="container">
  <h1 class="header">All Snippets</h1>

  <% current_user.snippets.each do |s| %>
    <div class="snippet">
      <%= render 'tags/info', snip: s %> 
      <p><%= s.content %></p>
    </div>
  <% end %>
</div>

app/views/staticpages/index.html.erb
<h1>Hello from Root url</h1>
<a href="javascript:<%= bookmarklet_caller_js %>">highlight text</a>

app/views/tags/_info.html.erb
<small>Created <%= time_ago_in_words(snip.created_at) %> ago. Tags: 
  <% snip.tags.each do |tag| %>
    <%= link_to tag.content.capitalize, tag_path(tag) %>
  <% end %>
</small>

app/views/tags/index.html.erb
<div class="tags all-tags">
  <h1>Tags</h1>
  <ul>
    <% current_user.tags.each do |t| %>
      <li class="tag"><%= link_to t.content.capitalize, t %></li>
    <% end %>
  </ul>
</div>

app/views/tags/show.html.erb
<div class="container">
  <h1 class="header"><%= @tag.content.capitalize %></h1>
  <% @snippets.each do |snip| %>
    <div class="snippet">
      <%= render 'tags/info', snip: snip %>
      <p><%= snip.content %></p>
    </div>
  <% end %>
</div>

app/views/users/_signup.html.erb
<div class="sign-up">
  <%= form_for @user, remote: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render 'shared/user_fields', f: f %>
    <%= f.submit "Sign Up" %>
  <% end %>
  <small class="toggle"><a href="#">Log In</a></small>
</div>

app/views/users/create.js.erb
<% if current_user %>
$('.sign-up').remove();
$('.sign-in').remove();
$('div.top a.disabled').remove();
$('div.top').append('<a class="bookmarklet" href="javascript:<%= bookmarklet_caller_js %>">DRAG ME</a>');
$('nav').append('<%= j render "layouts/signed_in" %>');
$('nav').find('div.alert').remove();
$('nav').prepend('<div class="alert">Successfully signed up');
<% else %>
  $('nav').prepend('<div class="alert">Error in signing up');
<% end %>

app/views/users/new.html.erb
<%= content_for :page_specific_javascript do  %>
  <%= javascript_include_tag "frontpage" %>
<% end %>
	<p class="sub-header">An easy way to save your text snippets.</p>
<div class="container">
  <div class="top">
	<% unless current_user %>
		<%= render 'users/signup' %>
		<%= render 'sessions/signin' %>
		<a class="disabled">DRAG ME</a>
	<% else %>
	  <a class="bookmarklet" href="javascript:<%= bookmarklet_caller_js %>">DRAG ME</a>
	<% end %>
  </div>

  <div class="explanation">
    <div class="info">
      <h2>What?</h2>
      <p>Snipp-et is a bookmarklet that allows you to save text snippets from all over the web.</p>
    </div>
    <div class="info"> 
      <h2>How?</h2>
      <p>Signup or Login. Drag the bookmarklet to your bookmark bar. Select any piece of text and click the bookmarklet.</p>
    </div>
    <div class="info">
      <h2>Why?</h2>
      <p>All the ideas, quotes, stories etc. you come across on the web in one place.Snipp-et provides a clean interface to navigate through them.</p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= content_for :page_specific_javascript do %>
  <%= javascript_include_tag "frontpage" %>
<% end %>
<div class="profile">
<a class="bookmarklet" href="javascript:<%= bookmarklet_caller_js %>">DRAG ME</a>
<h1>My Profile</h1>
<div class="tags">
  <h2>Popular Tags<%= link_to "View all", tags_path, class: "index" %></h2>
<% @user.tags.limit(5).each do |tag| %>
  <ul>
    <li class="tag"><%= link_to tag.content.capitalize, tag %></li>
  </ul>
<% end %>
</div>

<div class="snippets">
  <h2>Latest Snippets<%= link_to "View all", "/snippets", class: "index" %></h2>
  <div class="snippet">
    <% @user.snippets.limit(5).each do |s| %>
      <%= render 'tags/info', snip: s %>
      <a href="/snippets/<%= s.id %>" class="snippet">  <%= truncate(s.content, length: 200) %></a>
    <% end %>
  </div>
</div>
</div>